In [31]:
#import libraries
import numpy as np
import pandas as pd
import warnings
warnings.filterwarnings('ignore')

In [32]:
#importing dataset

ds=pd.read_csv('college_dropout_risk_rich_uncleaned.csv')
ds

current_gpa  attendance_rate  study_hours_per_week  financial_stress  \
0           3.85             81.6                   NaN                 6   
1           4.00             58.1                  18.5                 5   
2           2.45             78.7                  18.0                 6   
3           1.59             66.3                  27.2                 1   
4           3.23             64.9                  26.7                 9   
..           ...              ...                   ...               ...   
495         2.69             87.5                   2.1                 9   
496         3.38             41.8                   NaN                10   
497         3.14             82.3                   4.0                10   
498         3.67             62.7                  10.4                 2   
499         2.96             79.3                  14.8                 1   

     mental_health_score part_time_job parental_support  dropout_risk  
0                      6           Yes              low          0.39  
1                      5           Yes             high          0.33  
2                      2            No             high          0.39  
3                      7            No             high          0.30  
4                     10            No           medium          0.37  
..                   ...           ...              ...           ...  
495                    2           Yes           medium          0.51  
496                    5            No              low          0.56  
497                    8            No           medium          0.38  
498                    9            No           medium          0.22  
499                    1            No           medium          0.32  

[500 rows x 8 columns]

In [33]:
ds.columns


Index(['current_gpa', 'attendance_rate', 'study_hours_per_week',
       'financial_stress', 'mental_health_score', 'part_time_job',
       'parental_support', 'dropout_risk'],
      dtype='object')

In [34]:
#handling current_gpa column

ds['current_gpa'].unique()

array([3.85, 4.  , 2.45, 1.59, 3.23, 3.56, 2.64, 2.44, 2.21, 3.33, 2.76,
       2.58, 3.05, 2.53, 3.43, 3.47, 2.85, 2.47, 2.98, 1.67, 2.84,  nan,
       3.03, 2.12, 2.96, 2.88, 3.04, 2.33, 2.62, 2.65, 1.8 , 2.72, 2.79,
       2.67, 3.24, 2.35, 2.06, 1.71, 3.15, 3.14, 3.38, 3.71, 1.87, 2.3 ,
       3.02, 2.78, 3.2 , 2.26, 2.87, 3.12, 3.69, 2.22, 2.01, 2.05, 2.24,
       2.83, 2.82, 3.01, 1.41, 2.27, 2.23, 1.95, 3.5 , 2.51, 2.2 , 3.82,
       3.48, 3.22, 0.53, 1.92, 1.43, 2.75, 2.1 , 2.38, 2.08, 2.13, 2.63,
       2.32, 3.42, 1.61, 2.39, 2.61, 1.93, 2.43, 2.81, 3.41, 2.95, 3.28,
       1.79, 3.76, 3.13, 3.  , 3.52, 2.34, 1.68, 2.19, 2.14, 1.37, 2.97,
       3.06, 3.54, 2.93, 3.4 , 3.44, 3.37, 1.82, 2.7 , 3.91, 1.99, 2.86,
       2.4 , 3.16, 2.29, 1.83, 1.81, 2.46, 2.41, 0.97, 2.92, 3.35, 1.49,
       2.17, 1.96, 2.16, 2.91, 3.63, 3.95, 3.58, 1.6 , 2.11, 3.6 , 3.61,
       3.9 , 1.35, 2.48, 3.83, 2.89, 2.25, 3.25, 1.74, 2.71, 3.26, 3.32,
       3.07, 2.73, 3.34, 3.98, 3.78, 2.15, 3.59, 3.

In [35]:
ds['current_gpa'] = pd.to_numeric(ds['current_gpa'], errors='coerce') 

x=ds['current_gpa'].mean()
print(x)
ds['current_gpa'].fillna(x,inplace=True)

2.7893877551020405


In [37]:
ds['attendance_rate'] = pd.to_numeric(ds['attendance_rate'], errors='coerce')

x=ds['attendance_rate'].mean()
print(x)
ds['attendance_rate'].fillna(x,inplace=True)

75.10387755102042


In [40]:
#handling 'study_hours_per_week' column

ds['study_hours_per_week'].unique()

array([15.9, 18.5, 18. , 27.2, 26.7, 14.1,  8.1, 29.5, 18.9, 23.7, 20.1,
       12.9, 15.6, 21.4, 26.9, 13.5, 13.7, 19.3, 10.6, 17.9, 16.6,  4.9,
       23.3, 16.7,  0. ,  5.7, 25.3, 25.4, 16.2, 17.7,  9.4,  8.7, 23.4,
       14.6, 16.1, 17.3, 18.4,  5.1, 15.1, 17.2, 32.5, 24.8, 10.3, 24.7,
       21.2, 13. , 31.8, 17.8, 14.2, 30. , 11.9,  9.7, 16. , 22.2,  5. ,
       14. , 14.4, 13.8, 21. , 26.5, 22.5, 17. ,  1.2, 23.1, 16.3, 14.3,
       14.7, 18.7, 18.8,  3.3, 22.3,  9.5, 14.8,  5.4,  4.7, 28.4, 15.5,
       12.4, 11.1, 10.5, 19.5,  4.6, 23.8, 14.9,  7.3, 19. ,  3.1, 33.2,
       10.8, 18.2, 25.9,  3.7,  9.6,  7.7, 10. , 15.3, 20.7, 15. , 33.1,
       21.5, 15.8, 12.8, 26. , 20.8, 10.2, 16.9, 16.4,  7. , 12.6, 12.7,
        9.1, 21.3, 25.5, 10.7, 10.9,  4.1, 13.2, 19.1, 17.6,  9.2, 22. ,
       16.8, 11.8, 22.7,  2.8, 13.3, 17.1, 18.6, 25.7,  4. ,  5.6, 11. ,
       18.1, 19.2, 19.7,  8.4,  6. , 10.1, 22.1, 11.3, 19.6, 11.7, 23.5,
        6.5, 29.4,  2.7, 15.4, 11.6, 24.2, 23.6, 11

In [41]:
ds['study_hours_per_week'] = pd.to_numeric(ds['study_hours_per_week'], errors='coerce')

x=ds['study_hours_per_week'].median()
print(x)
ds['study_hours_per_week'].fillna(x,inplace=True)

15.9


In [42]:
ds.columns

Index(['current_gpa', 'attendance_rate', 'study_hours_per_week',
       'financial_stress', 'mental_health_score', 'part_time_job',
       'parental_support', 'dropout_risk'],
      dtype='object')

In [49]:
#handling 'financial_stress' column

ds['financial_stress'].unique()

array([ 6,  5,  1,  9,  8, 10,  4,  2,  3,  7], dtype=int64)

In [48]:
ds['financial_stress'] = pd.to_numeric(ds['financial_stress'], errors='coerce')

In [51]:
ds.head(20)

current_gpa  attendance_rate  study_hours_per_week  financial_stress  \
0          3.85             81.6                  15.9                 6   
1          4.00             58.1                  18.5                 5   
2          2.45             78.7                  18.0                 6   
3          1.59             66.3                  27.2                 1   
4          3.23             64.9                  26.7                 9   
5          3.56             72.2                  14.1                 8   
6          2.64             56.7                   8.1                10   
7          2.44            100.0                  29.5                10   
8          2.21             85.7                  18.9                 8   
9          3.33             91.5                  23.7                 8   
10         2.76             66.5                  20.1                 6   
11         2.58             88.3                  12.9                 4   
12         3.05             58.8                  15.6                 2   
13         2.53             90.6                  20.1                 4   
14         2.44             74.3                  23.7                 8   
15         3.43             74.4                  21.4                 3   
16         3.47             80.3                  26.9                 8   
17         2.85             59.9                  13.5                 5   
18         2.47             77.6                  13.7                 2   
19         4.00             63.4                  19.3                10   

    mental_health_score part_time_job parental_support  dropout_risk  
0                     6           Yes              low          0.39  
1                     5           Yes             high          0.33  
2                     2            No             high          0.39  
3                     7            No             high          0.30  
4                    10            No           medium          0.37  
5                     2           Yes             high          0.43  
6                     4           Yes             high          0.53  
7                     3           Yes              low          0.55  
8                     1            No              low          0.54  
9                     1            No           medium          0.41  
10                   10           Yes             high          0.33  
11                    4           Yes             high          0.34  
12                    7           Yes              low          0.40  
13                    8            No           medium          0.28  
14                    3            No             high          0.43  
15                    7           Yes              low          0.35  
16                    6            No              low          0.40  
17                    2           Yes             high          0.44  
18                    7           Yes           medium          0.34  
19                    6           Yes           medium          0.45

In [50]:
#handling 'mental_halth._score' column

ds['mental_health_score'].unique()

array([ 6,  5,  2,  7, 10,  4,  3,  1,  8,  9], dtype=int64)

In [52]:
ds['mental_health_score'] = pd.to_numeric(ds['mental_health_score'], errors='coerce')

In [55]:
#handling part_time_job column

ds['part_time_job'].unique()

array([1, 0], dtype=int64)

In [56]:
ds['part_time_job'] = ds['part_time_job'].replace({'Yes': 1, 'No': 0})

In [57]:
#handling 'parental_support' column
ds['parental_support'].unique()

array(['low', 'high', 'medium'], dtype=object)

In [58]:
ds['parental_support'] = ds['parental_support'].replace({' Medium': 'medium', 'LOW': 'low', 'High': 'high'})

In [59]:
#handling dropout_risk column

ds['dropout_risk'].unique()

array([0.39, 0.33, 0.3 , 0.37, 0.43, 0.53, 0.55, 0.54, 0.41, 0.34, 0.4 ,
       0.28, 0.35, 0.44, 0.45, 0.58, 0.48, 0.46, 0.26, 0.25, 0.47, 0.27,
       0.32, 0.22, 0.24, 0.64, 0.31, 0.38, 0.49, 0.61, 0.42, 0.5 , 0.15,
       0.52, 0.18, 0.36, 0.29, 0.51, 0.21, 0.56, 0.57, 0.23, 0.2 , 0.6 ,
       0.68, 0.62, 0.59, 0.16, 0.65, 0.17, 0.19])

In [60]:
ds['dropout_risk'] = pd.to_numeric(ds['dropout_risk'], errors='coerce')

x=ds['dropout_risk'].mean()
print(x)
ds['dropout_risk'].fillna(x,inplace=True)

0.39433999999999997


In [61]:
ds.head(20)

current_gpa  attendance_rate  study_hours_per_week  financial_stress  \
0          3.85             81.6                  15.9                 6   
1          4.00             58.1                  18.5                 5   
2          2.45             78.7                  18.0                 6   
3          1.59             66.3                  27.2                 1   
4          3.23             64.9                  26.7                 9   
5          3.56             72.2                  14.1                 8   
6          2.64             56.7                   8.1                10   
7          2.44            100.0                  29.5                10   
8          2.21             85.7                  18.9                 8   
9          3.33             91.5                  23.7                 8   
10         2.76             66.5                  20.1                 6   
11         2.58             88.3                  12.9                 4   
12         3.05             58.8                  15.6                 2   
13         2.53             90.6                  20.1                 4   
14         2.44             74.3                  23.7                 8   
15         3.43             74.4                  21.4                 3   
16         3.47             80.3                  26.9                 8   
17         2.85             59.9                  13.5                 5   
18         2.47             77.6                  13.7                 2   
19         4.00             63.4                  19.3                10   

    mental_health_score  part_time_job parental_support  dropout_risk  
0                     6              1              low          0.39  
1                     5              1             high          0.33  
2                     2              0             high          0.39  
3                     7              0             high          0.30  
4                    10              0           medium          0.37  
5                     2              1             high          0.43  
6                     4              1             high          0.53  
7                     3              1              low          0.55  
8                     1              0              low          0.54  
9                     1              0           medium          0.41  
10                   10              1             high          0.33  
11                    4              1             high          0.34  
12                    7              1              low          0.40  
13                    8              0           medium          0.28  
14                    3              0             high          0.43  
15                    7              1              low          0.35  
16                    6              0              low          0.40  
17                    2              1             high          0.44  
18                    7              1           medium          0.34  
19                    6              1           medium          0.45

In [62]:
#saving cleaned dataset
ds.to_csv('dropout_risk_cleaned.csv')